GET http://localhost:8080/api/projetos
Accept: application/json

###
POST http://localhost:8080/api/projetos
Content-Type: application/json

{
    "nome":"erik"
}

###
DELETE http://localhost:8080/api/projetos/fc90ee39-2e1c-48d0-a700-d5f0c62ec5b3

###Altera status do Projeto
PATCH http://localhost:8080/api/projetos/bf1ad4ec-f877-4ad3-9a41-cc451b2c3f27
Content-Type: application/json

{
    "status": false
}

###
PUT http://localhost:8080/api/projetos/15ad0a0a-01bd-4d17-b92b-deb1d46d5328
Content-Type: application/json

{
    "nome": "Teste 2",
    "status": false
}