GET http://localhost:8080/api/projetos
Accept: application/json

###
POST http://localhost:8080/api/projetos
Content-Type: application/json

{
    "nome":"compass"
}

###
DELETE http://localhost:8080/api/projetos/ba93a2da-850e-4a27-ac9b-9efbab53e9b5

###Altera status do Projeto
PATCH http://localhost:8080/api/projetos/7d68a823-494e-4bde-aac3-4b61fb6919ac
Content-Type: application/json

{
    "status": false
}

###
PUT http://localhost:8080/api/projetos/7d68a823-494e-4bde-aac3-4b61fb6919ac
Content-Type: application/json

{
    "nome": "Teste 2",
    "status": true
}